# Generated by Django 3.0.5 on 2020-05-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entertainment_areas',
            old_name='area_coordinates_altitude',
            new_name='area_coordinates_longitude',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_coordinates_altitude',
            new_name='event_coordinates_longitude',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_coordinates_altitude',
            new_name='workshop_coordinates_longitude',
        ),
        migrations.AlterField(
            model_name='entertainment_areas',
            name='image_route',
            field=models.ImageField(blank=True, null=True, upload_to='areas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image_route',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/%Y/%m/%d'),
        ),
    ]
