# Generated by Django 3.0.5 on 2020-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi_app', '0002_auto_20200502_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment_areas',
            name='area_ended_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entertainment_areas',
            name='area_start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event_type',
            name='event_type_icon',
            field=models.ImageField(blank=True, null=True, upload_to='events_type/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='workshop_type',
            name='workshop_type_icon',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_type/%Y/%m/%d'),
        ),
    ]
