# Generated by Django 3.0.5 on 2020-05-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapi_app', '0003_auto_20200526_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment_areas',
            name='icon_route',
            field=models.ImageField(blank=True, null=True, upload_to='areas/icons/%Y/%m/%d'),
        ),
    ]
