# Generated by Django 3.0.5 on 2020-05-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapi_app', '0004_entertainment_areas_icon_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Entertainment_areas'),
        ),
        migrations.AddField(
            model_name='entertainment_areas',
            name='five_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entertainment_areas',
            name='four_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entertainment_areas',
            name='one_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entertainment_areas',
            name='three_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entertainment_areas',
            name='two_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='five_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='four_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='one_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='three_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workshop',
            name='two_stars',
            field=models.IntegerField(default=0),
        ),
    ]
