# Generated by Django 3.0.5 on 2020-04-26 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(default='', max_length=255)),
                ('event_type_description', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Sin identificar', max_length=10)),
                ('table_name', models.CharField(default='Sin identificar', max_length=100)),
                ('action', models.CharField(default='Sin especificar', max_length=100)),
                ('description', models.CharField(blank=True, default='Sin descripción', max_length=500, null=True)),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('log_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_type_name', models.CharField(default='', max_length=255)),
                ('workshop_type_description', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(default='Sin nombre', max_length=255)),
                ('workshop_address', models.CharField(default='Sin indicar', max_length=500)),
                ('image_route', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d')),
                ('workshop_coordinates_altitude', models.CharField(max_length=100)),
                ('workshop_coordinates_latitude', models.CharField(max_length=100)),
                ('workshop_quotas', models.IntegerField(default=-1)),
                ('workshop_description', models.CharField(blank=True, default='Sin descripción', max_length=500, null=True)),
                ('workshop_days', models.CharField(default='Sin especificar', max_length=13)),
                ('workshop_start_date', models.DateField(auto_now_add=True)),
                ('workshop_ended_date', models.DateField(auto_now_add=True)),
                ('workshop_start_time', models.TimeField(auto_now_add=True)),
                ('workshop_ended_time', models.TimeField(auto_now_add=True)),
                ('workshop_available', models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=1)),
                ('workshop_commune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Commune')),
                ('workshop_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Workshop_type')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('birthday', models.DateField(auto_now_add=True, null=True)),
                ('marital_situation', models.IntegerField(choices=[(0, 'Casado(a)'), (1, 'Separado(a) Judicialmente'), (2, 'Divorciado(a)'), (3, 'Viudo(a)'), (4, 'Soltero(a)'), (5, 'Conviviente Civil')], default=4, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer'), (2, 'Prefiero no decir'), (3, 'Otro')], default=2, null=True)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Commune')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Sin nombre', max_length=255)),
                ('event_address', models.CharField(default='Sin indicar', max_length=500)),
                ('image_route', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d')),
                ('event_coordinates_altitude', models.CharField(max_length=100)),
                ('event_coordinates_latitude', models.CharField(max_length=100)),
                ('event_quotas', models.IntegerField(default=-1)),
                ('event_description', models.CharField(blank=True, default='Sin descripción', max_length=500, null=True)),
                ('event_start_date', models.DateField(auto_now_add=True)),
                ('event_ended_date', models.DateField(auto_now_add=True)),
                ('event_start_time', models.TimeField(auto_now_add=True)),
                ('event_ended_time', models.TimeField(auto_now_add=True)),
                ('event_available', models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=1)),
                ('one_stars', models.IntegerField(default=0)),
                ('two_stars', models.IntegerField(default=0)),
                ('three_stars', models.IntegerField(default=0)),
                ('four_stars', models.IntegerField(default=0)),
                ('five_stars', models.IntegerField(default=0)),
                ('event_commune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Commune')),
                ('event_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Event_type')),
            ],
        ),
        migrations.CreateModel(
            name='Entertainment_areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='Sin nombre', max_length=255)),
                ('area_address', models.CharField(default='Sin indicar', max_length=500)),
                ('image_route', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/%d')),
                ('area_coordinates_altitude', models.CharField(max_length=100)),
                ('area_coordinates_latitude', models.CharField(max_length=100)),
                ('area_description', models.CharField(blank=True, default='Sin descripción', max_length=500, null=True)),
                ('area_days', models.CharField(default='Sin especificar', max_length=13)),
                ('area_available', models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=1)),
                ('area_commune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Sin nombre', max_length=255)),
                ('comment_date', models.DateField(auto_now=True)),
                ('comment_time', models.TimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Event')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapi_app.Workshop')),
            ],
        ),
    ]
